### ISSUE TITLE
Is it compatible with visual studio for Mac resx files?

### ISSUE THREAD

**Issue by ajtruckle** [sebasbaumh/ResEx#1]
Thanks.

**Comment by sebasbaumh** [comment]
I would say yes as the format of the resx files should be pretty much the same.
But ResEx itself might only be working on Windows (I am not sure about Xamarin).

**Comment by ajtruckle** [comment]
Ok. Is it possible to supply this as a built executable so that I don't have to compile it?

**Comment by sebasbaumh** [comment]
I don't have a Mac so I am not able to compile it with Xamarin or something like that.
But I just compiled the Windows version and created this release: https://github.com/sebasbaumh/ResEx/releases/tag/v1.0.2
It is still the version from 2012 though as I did not use it very much in the last years.
